version: "3.8"

networks:
  internal_net:
    external: true

services:
  auth:
    build:
      context: ../../
      dockerfile: apps/auth/Dockerfile
      target: production
    env_file:
      - .env.prod
    ports:
      - "50001:3000"
    restart: always
    networks:
      - internal_net
