version: "3.8"

networks:
  internal_net:
    external: true

services:
  booking:
    build:
      context: ../../
      dockerfile: apps/booking/Dockerfile
      target: development
    volumes:
      - ./apps/booking:/app/apps/booking
      - ./libs/shared-common:/app/libs/shared-common
    env_file:
      - .env.dev
    ports:
      - "50002:3000" 
    networks:
      - internal_net
