version: "3.8"

networks:
  internal_net:
    external: true

services:
  booking:
    build:
      context: ../../
      dockerfile: apps/booking/Dockerfile
      target: production
    env_file:
      - .env.prod
    ports:
      - "50002:3000"
    restart: always
    networks:
      - internal_net
