version: "3.8"

networks:
  internal_net:
    external: true

services:
  verification:
    build:
      context: ../../
      dockerfile: apps/verification/Dockerfile
      target: production
    env_file:
      - .env.prod
    ports:
      - "50009:3000"
    restart: always
    networks:
      - internal_net
