version: "3.8"

networks:
  internal_net:
    external: true
  public_net:
    external: true

services:
  navigation:
    build:
      context: ../../
      dockerfile: apps/navigation/Dockerfile
      target: production
    env_file:
      - .env.prod
    ports:
      - "50005:3000"
    restart: always
    networks:
      - internal_net 
      - public_net