version: "3.8"

networks:
  internal_net:
    external: true
  public_net:
    external: true


services:
  api-gateway:
    build:
      context: ../../
      dockerfile: apps/api-gateway/Dockerfile
      target: development
    volumes:
      - ./apps/api-gateway:/app/apps/api-gateway
      - ./libs/shared-common:/app/libs/shared-common
    env_file:
      - .env.dev
    ports:
      - "3000:3000" 
    networks:
      - internal_net
      - public_net