version: "3.8"

networks:
  internal_net:
    external: true

services:
  payment:
    build:
      context: ../../
      dockerfile: apps/payment/Dockerfile
      target: production
    env_file:
      - .env.prod
    ports:
      - "50007:3000"
    restart: always
    networks:
      - internal_net
