version: "3.8"

networks:
  internal_net:
    external: true
  public_net:
    external: true


services:
  chat:
    build:
      context: ../../
      dockerfile: apps/chat/Dockerfile
      target: development
    volumes:
      - ./apps/chat:/app/apps/chat
      - ./libs/shared-common:/app/libs/shared-common
    env_file:
      - .env.dev
    ports:
      - "50003:3000" 
    networks:
      - internal_net
      - public_net